# Generated by Django 5.0.1 on 2024-03-13 02:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FurnishingRequest",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("request_time", models.DateTimeField(auto_now_add=True)),
                ("expire_time", models.DateTimeField()),
                ("Input_file_image", models.FileField(upload_to="uploads/")),
                ("Input_file_json", models.FileField(upload_to="uploads/")),
                (
                    "Output_file_image",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "Output_file_json",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
            ],
        ),
    ]
