# Generated by Django 5.0.1 on 2024-03-19 06:45

import frontend_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="furnishingrequest",
            name="Input_file_image",
        ),
        migrations.RemoveField(
            model_name="furnishingrequest",
            name="Input_file_json",
        ),
        migrations.RemoveField(
            model_name="furnishingrequest",
            name="Output_file_image",
        ),
        migrations.RemoveField(
            model_name="furnishingrequest",
            name="Output_file_json",
        ),
        migrations.AddField(
            model_name="furnishingrequest",
            name="input_file_image",
            field=models.FileField(
                blank=True, null=True, upload_to=frontend_api.models.upload_input_path
            ),
        ),
        migrations.AddField(
            model_name="furnishingrequest",
            name="input_file_json",
            field=models.FileField(
                blank=True, null=True, upload_to=frontend_api.models.upload_input_path
            ),
        ),
        migrations.AddField(
            model_name="furnishingrequest",
            name="output_file_image",
            field=models.FileField(
                blank=True, null=True, upload_to=frontend_api.models.upload_output_path
            ),
        ),
        migrations.AddField(
            model_name="furnishingrequest",
            name="output_file_json",
            field=models.FileField(
                blank=True, null=True, upload_to=frontend_api.models.upload_output_path
            ),
        ),
    ]
